### ISSUE TITLE
foldTree is incorrect

### ISSUE THREAD

**Issue by leshow** [dmvianna/haskellbook#2]
you're applying 'b' too many times in the signature for f in foldTree. you have (a -> b -> b -> b)

it should be (a -> b -> b) -- as written in the book. 

My solution was

``` haskell
foldTree :: (a -> b -> b) -> b -> BinTree a -> b
foldTree _ b Leaf                = b
foldTree f b (Node Leaf a Leaf)  = f a b
foldTree f b (Node left a right) = foldTree f (f a (foldTree f b left)) right
```

**Comment by pasunboneleve** [comment]
Incorrect or redundant?

And would you like to submit a pull request? I'm happy to merge.

**Comment by leshow** [comment]
I believe it is incorrect. If you tried to fold over the tree to collect the sum for example, the initial value would be applied too many times. Sure. I can submit a PR

edit: also, if you look in the book, you will see the function signature for yours is different.
